### ISSUE TITLE
what does this run on

### ISSUE THREAD

**Issue by Randomwasnotavailable** [BaronSwango/PokemonFireRedClone#1]
just wondering what does this run on?

**Comment by BaronSwango** [comment]
> just wondering what does this run on?

Windows and Mac currently. I'm gonna try to get it working on mobile once I get a more stable version of it done.

**Comment by Randomwasnotavailable** [comment]
like is it an exe file or does it have to launch on an engine?

**Comment by BaronSwango** [comment]
> like is it an exe file or does it have to launch on an engine?

Its an exe on windows or .app on mac, you have to package it tho which I have not done yet. One of these days I'll package it on both platforms and start posting the updated packaged games with every commit for each platform

**Comment by BaronSwango** [comment]
Not using an engine, just the monogame framework
